### ISSUE TITLE
unable to upload style 

### ISSUE THREAD

**Issue by liyoung47** [maplibre/maputnik#880] opened 2024-02-08 18:49 UTC
**Maputnik version**:v2.0.0
**Browser**:Firefox, Chrome
**OS**:macOS

**Description of the bug**:
We've used Maputnik for years to examine our custom styles, but just recently it has stopped working.
When we upload our custom style file, the map does not change to show the new style, even tho the left-hand panel shows the names of the layers from the new style

**Steps to reproduce the behavior**:
1. launch Chrome incognito (to be sure of a fresh start) and visit `https://maplibre.org/maputnik`. OSM Liberty is displayed by default
2. choose Open > Upload and select local json style file

expected: new style is displayed
actual: the layers in the left bar reflect the local json style, but OSM Liberty is still displayed on the map.

**Style file or style URL**:
I'm not able to share our style files, but the identical style files worked as recently as a few weeks ago, and are still working in our client apps with regular maplibre.

**Screenshots**:
video: attempt to upload style, from fresh state:
https://github.com/maplibre/maputnik/assets/5832047/089a4e37-f286-4265-8881-f073138ff983

**Comment by HarelM** [comment] 2024-02-08 18:54
Can you check if this is the same issue as: #871
i.e. if you refresh the browser after you load the style it will work?

**Comment by liyoung47** [comment] 2024-02-08 19:27
When I refresh the browser after upload, the map looks like what I was expecting.

in #871 they went from an uploaded style to a built-in style and saw a merged result. When I go from the uploaded style (which I only get after refreshing) to the built-in style, the built-in style looks fine.

I _was_ able to get into a merged state earlier...I took screenshots but have not been able get into this state again. following the steps in #871 has not produced it

map with merged state: square is OSM Liberty, rest is uploaded style
<img width="1530" alt="merged style" src="https://github.com/maplibre/maputnik/assets/5832047/682af5a9-2834-45d3-9179-4ddd935a7e96">

inspection with merged state: the source "omv: water" is from my style, the "openmaptiles: transportation" is from one of the built-in styles as my style has no source with that name
<img width="1528" alt="merged style inspection" src="https://github.com/maplibre/maputnik/assets/5832047/4a7a27a0-08b7-45d0-b76e-a14737aa0b0e">

**Comment by liyoung47** [comment] 2024-02-08 22:06
I don't mind if you want to close if you think its a duplicate.
If I'm able to replicate the merged state again I'll check and see if refreshing fixes it.

**Comment by HarelM** [comment] 2024-02-09 12:13
Closing as duplicate of #871.
I'll gladly reopen if this is not the same once the other issue is fixed.

**Closed by HarelM** 2024-02-09 12:13 UTC
