### ISSUE TITLE
Tiles do not load when first loading another style

### ISSUE THREAD

**Issue by pnorman** [maplibre/maputnik#882] opened 2024-02-14 18:47 UTC
**Maputnik version**: v2.0.0
**Browser**: 121.0.6167.161 (Official Build) (64-bit) (cohort: Control)
**OS**: Windows 11
**Description of the bug**: Tiles do not load after loading another style

**Steps to reproduce the behavior**:
1. Open https://maplibre.org/maputnik in a new window with developer tools open
2. Open -> Gallery Styles -> Empty Styles to start an empty style
3. Open -> Upload Style -> Upload using the attached file

**Style file or style URL**: [neutrino.json](https://github.com/maplibre/maputnik/files/14284909/neutrino.json)

Looking at the dev console no HTTP requests are sent for the tiles.

This issue is not specific to this style or tile source. You do not need to be serving tiles locally to test this as it doesn't even make the HTTP requests.

**Comment by nyurik** [comment] 2024-02-14 18:51
CC @HarelM ... I wonder if we should restore the original maputnik in the mean time (at the original location)...

**Comment by HarelM** [comment] 2024-02-14 18:54
Sure, as I said, I don't think it should've been removed...

I believe this is a duplicate of: 
- #871

**Comment by birkskyum** [comment] 2024-02-14 19:07
pr here - add all these old versions back:
https://github.com/maputnik/maputnik.github.io/pull/32

**Comment by HarelM** [comment] 2024-03-09 20:45
Closing this as a duplicate of #871, A PR with a short term fix is ready #885, once merged to main the fix will be published if this issue is not resolved, please ping here and I'll be happy to reopen the issue.

**Closed by HarelM** 2024-03-09 20:45 UTC
